CREATE DATABASE MyFuncDB
 ON  PRIMARY 
( NAME = N'MyFuncDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\MyFuncDB.mdf' , SIZE = 30720KB , MAXSIZE = 102400KB , FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'MyFuncDB_log', FILENAME = N'D:\Temp\MyFuncDB_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB)
COLLATE Ukrainian_100_CI_AS